### ISSUE TITLE
Could not generate snippet 

### ISSUE THREAD

**Issue by RalphBergmannKMB** [zeplin/cli-connect-swift-plugin#13]
When I call `zeplin connect` I get this result:

```
Zeplin CLI - v1.1.11


Connecting components to Zeplin components failed.

    Error occurred while processing Panelist/Account/PlSecureField.swift with @zeplin/cli-connect-swift-plugin:

    Could not generate snippet on Panelist/Account/PlSecureField.swift

Please check /Users/ralphbergmann/.zeplin/cli.log for details.
```

And this is the content of the log file:
```
2021-04-27 12:23:51 - info -
Zeplin CLI - v1.1.11

2021-04-27 12:23:51 - debug - connect options: {"configFiles":[],"devMode":false,"devModePort":9756,"devModeWatch":true,"plugins":[]}
2021-04-27 12:23:51 - debug - component config files: [{"plugins":[{"name":"@zeplin/cli-connect-swift-plugin"}],"projects":["xxx"],"styleguides":["xxx"],"components":[{"path":"Panelist/Account/PlSecureField.swift","zeplinIds":["xxx"]}]}]
2021-04-27 12:23:51 - debug - Initializing @zeplin/cli-connect-swift-plugin.
2021-04-27 12:23:51 - debug - @zeplin/cli-connect-swift-plugin supports Panelist/Account/PlSecureField.swift. Processing…
2021-04-27 12:23:51 - error -
Connecting components to Zeplin components failed.

    Error occurred while processing Panelist/Account/PlSecureField.swift with @zeplin/cli-connect-swift-plugin:

    Could not generate snippet on Panelist/Account/PlSecureField.swift
2021-04-27 12:23:51 - debug - Error: Connecting components to Zeplin components failed.

    Error occurred while processing Panelist/Account/PlSecureField.swift with @zeplin/cli-connect-swift-plugin:

    Could not generate snippet on Panelist/Account/PlSecureField.swift
    at /usr/local/lib/node_modules/@zeplin/cli/dist/src/commands/connect/plugin.js:187:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@zeplin/cli/dist/src/commands/connect/plugin.js:25:65)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
2021-04-27 12:23:51 - debug - "TypeError: Cannot read property 'key.name' of undefined\n    at default_1.<anonymous> (/usr/local/lib/node_modules/@zeplin/cli-connect-swift-plugin/dist/index.js:72:54)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/lib/node_modules/@zeplin/cli-connect-swift-plugin/dist/index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:93:5)"
2021-04-27 12:23:51 - info -
Please check /Users/ralphbergmann/.zeplin/cli.log for details.
```

Do you have any idea how to fix this? Or am I doing something wrong?

**Comment by yuqu** [comment]
Hi, it seems the plugin could not find the class declaration on sourcekitten output. I can investigate thoroughly if you could share a sample of the component file.

**Comment by RalphBergmannKMB** [comment]
Today at 2 p.m. (CEST), I have a meeting with my designer to start a small project from scratch, and after that, I also have something to share with you.
