### ISSUE TITLE
Could not generate snippet

### ISSUE THREAD

**Issue by marcelderkskarlmax** [zeplin/cli-connect-swift-plugin#20]
Hello ! 

I tried to use this plugin for zeplin components but was not able to get a connection between code and zeplin project.

The installation of the tools was no problem and I managed to set the json configuration file up.

But when running 
`zeplin connect --verbose` 
I get the following output.

```
Error: Connecting components to Zeplin components failed.

    Error occurred while processing ZeplinComponentsTest/Components/TestComponentButton.swift with @zeplin/cli-connect-swift-plugin:

    Could not generate snippet on ZeplinComponentsTest/Components/TestComponentButton.swift
    at /usr/local/lib/node_modules/@zeplin/cli/dist/src/commands/connect/plugin.js:187:19
    at Generator.throw (<anonymous>)
    at rejected (/usr/local/lib/node_modules/@zeplin/cli/dist/src/commands/connect/plugin.js:25:65)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
Details:
"TypeError: Cannot read property 'filter' of undefined\n    at default_1.<anonymous> (/usr/local/lib/node_modules/@zeplin/cli-connect-swift-plugin/dist/index.js:75:22)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/local/lib/node_modules/@zeplin/cli-connect-swift-plugin/dist/index.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:94:5)"
```

My questions: 

Is this plugin supposed to run with both: SwiftUI and UIKit ?
How do I have to prepare the reusable component in code ?
In the readme is a todo stating that documentation is missing.
Is this documentation provided anytime soon ? 

Thanks for answers :-)

**Comment by emaKarlmax** [comment]
yes, please complete the documentation here:
<TODO: Describe what types of Swift classes are supported with examples.>
